# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: active_event 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "active_event"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Douglas Camata"]
  s.date = "2014-07-10"
  s.description = "    Watch for a method call in any class and run before/after callbacks.\n    You can even watch your Rails models for events (like create, update,\n    destroy), send these events to a event-runner instance and it redirect these\n    events to other apps that are subscrived for them. This gem also provides\n    classes that you can use to process the received events too.\n"
  s.email = "d.camata@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rbenv-gemsets",
    ".rspec",
    ".rubocop.yml",
    ".ruby-version",
    ".yardopts",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "active_event.gemspec",
    "app/controllers/active_event/notifications_controller.rb",
    "config/initializers/active_event_configuration_loader.rb",
    "config/routes.rb",
    "lib/active_event.rb",
    "lib/active_event/base.rb",
    "lib/active_event/configuration.rb",
    "lib/active_event/rails/base.rb",
    "lib/active_event/rails/engine.rb",
    "lib/active_event/rails/hook_list.rb",
    "lib/active_event/rails/listener.rb",
    "lib/active_event/rails/railtie.rb",
    "lib/active_event/rails/spy.rb",
    "lib/active_event/spy/spy.rb",
    "lib/active_event/spy/spy_list.rb",
    "lib/rails/generators/active_event/install/install_generator.rb",
    "lib/rails/generators/active_event/install/templates/active_event.yml",
    "lib/rails/generators/active_event/install/templates/initializer.rb",
    "spec/active_event/base_spec.rb",
    "spec/active_event/configuration_spec.rb",
    "spec/active_event/rails_event_handler_spec.rb",
    "spec/active_event/spy_spec.rb",
    "spec/rails_integration/dummy/.gitignore",
    "spec/rails_integration/dummy/.rbenv-gemsets",
    "spec/rails_integration/dummy/Gemfile",
    "spec/rails_integration/dummy/Gemfile.lock",
    "spec/rails_integration/dummy/README.rdoc",
    "spec/rails_integration/dummy/Rakefile",
    "spec/rails_integration/dummy/app/assets/images/.keep",
    "spec/rails_integration/dummy/app/assets/javascripts/application.js",
    "spec/rails_integration/dummy/app/assets/stylesheets/application.css",
    "spec/rails_integration/dummy/app/controllers/application_controller.rb",
    "spec/rails_integration/dummy/app/controllers/concerns/.keep",
    "spec/rails_integration/dummy/app/events/product_events.rb",
    "spec/rails_integration/dummy/app/events/user_events.rb",
    "spec/rails_integration/dummy/app/helpers/application_helper.rb",
    "spec/rails_integration/dummy/app/mailers/.keep",
    "spec/rails_integration/dummy/app/models/.keep",
    "spec/rails_integration/dummy/app/models/concerns/.keep",
    "spec/rails_integration/dummy/app/models/product.rb",
    "spec/rails_integration/dummy/app/models/user.rb",
    "spec/rails_integration/dummy/app/views/layouts/application.html.erb",
    "spec/rails_integration/dummy/bin/bundle",
    "spec/rails_integration/dummy/bin/rails",
    "spec/rails_integration/dummy/bin/rake",
    "spec/rails_integration/dummy/config.ru",
    "spec/rails_integration/dummy/config/active_event.yml",
    "spec/rails_integration/dummy/config/application.rb",
    "spec/rails_integration/dummy/config/boot.rb",
    "spec/rails_integration/dummy/config/database.yml",
    "spec/rails_integration/dummy/config/environment.rb",
    "spec/rails_integration/dummy/config/environments/development.rb",
    "spec/rails_integration/dummy/config/environments/production.rb",
    "spec/rails_integration/dummy/config/environments/test.rb",
    "spec/rails_integration/dummy/config/initializers/active_event.rb",
    "spec/rails_integration/dummy/config/initializers/assets.rb",
    "spec/rails_integration/dummy/config/initializers/backtrace_silencers.rb",
    "spec/rails_integration/dummy/config/initializers/cookies_serializer.rb",
    "spec/rails_integration/dummy/config/initializers/filter_parameter_logging.rb",
    "spec/rails_integration/dummy/config/initializers/inflections.rb",
    "spec/rails_integration/dummy/config/initializers/mime_types.rb",
    "spec/rails_integration/dummy/config/initializers/session_store.rb",
    "spec/rails_integration/dummy/config/initializers/wrap_parameters.rb",
    "spec/rails_integration/dummy/config/locales/en.yml",
    "spec/rails_integration/dummy/config/routes.rb",
    "spec/rails_integration/dummy/config/secrets.yml",
    "spec/rails_integration/dummy/db/migrate/20140630185459_create_users.rb",
    "spec/rails_integration/dummy/db/migrate/20140701192021_create_products.rb",
    "spec/rails_integration/dummy/db/migrate/20140703173352_add_guid_to_product.rb",
    "spec/rails_integration/dummy/db/schema.rb",
    "spec/rails_integration/dummy/db/seeds.rb",
    "spec/rails_integration/dummy/lib/assets/.keep",
    "spec/rails_integration/dummy/lib/tasks/.keep",
    "spec/rails_integration/dummy/log/.keep",
    "spec/rails_integration/dummy/public/404.html",
    "spec/rails_integration/dummy/public/422.html",
    "spec/rails_integration/dummy/public/500.html",
    "spec/rails_integration/dummy/public/favicon.ico",
    "spec/rails_integration/dummy/public/robots.txt",
    "spec/rails_integration/dummy/spec/product_spec.rb",
    "spec/rails_integration/dummy/spec/spec_helper.rb",
    "spec/rails_integration/dummy/spec/user_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/edools/active_event"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Watch for a method call in any class and run before/after callbacks. Has good integration with Rails."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 4.1.2"])
      s.add_runtime_dependency(%q<rest-client>, ["= 1.6.7"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_development_dependency(%q<activerecord>, ["~> 4.1.2"])
      s.add_development_dependency(%q<rails>, ["~> 4.1.2"])
      s.add_development_dependency(%q<rubocop>, ["~> 0.24.0"])
      s.add_development_dependency(%q<pry>, ["~> 0.10.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.0.0"])
      s.add_development_dependency(%q<yard>, ["= 0.8.7.4"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.1.1"])
      s.add_development_dependency(%q<bundler>, ["~> 1.6.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, ["~> 4.1.2"])
      s.add_dependency(%q<rest-client>, ["= 1.6.7"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<activerecord>, ["~> 4.1.2"])
      s.add_dependency(%q<rails>, ["~> 4.1.2"])
      s.add_dependency(%q<rubocop>, ["~> 0.24.0"])
      s.add_dependency(%q<pry>, ["~> 0.10.0"])
      s.add_dependency(%q<rspec>, ["~> 3.0.0"])
      s.add_dependency(%q<yard>, ["= 0.8.7.4"])
      s.add_dependency(%q<rdoc>, ["~> 4.1.1"])
      s.add_dependency(%q<bundler>, ["~> 1.6.3"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 4.1.2"])
    s.add_dependency(%q<rest-client>, ["= 1.6.7"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<activerecord>, ["~> 4.1.2"])
    s.add_dependency(%q<rails>, ["~> 4.1.2"])
    s.add_dependency(%q<rubocop>, ["~> 0.24.0"])
    s.add_dependency(%q<pry>, ["~> 0.10.0"])
    s.add_dependency(%q<rspec>, ["~> 3.0.0"])
    s.add_dependency(%q<yard>, ["= 0.8.7.4"])
    s.add_dependency(%q<rdoc>, ["~> 4.1.1"])
    s.add_dependency(%q<bundler>, ["~> 1.6.3"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

