source 'https://rubygems.org'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.2'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
gem 'rspec-rails', '~> 3.0.1', group: :test
gem 'spring-commands-rspec'

gem 'active_event', path: "../../../"
